=== digilinq/trade-items/src/main/resources/xml/person.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Define complex type for address -->
    <xs:complexType name="Address">
        <xs:sequence>
            <xs:element name="street" type="xs:string"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="postalCode" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PersonType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="lastName" type="xs:string"/>
            <xs:element name="birthday" type="xs:date"/>
            <xs:element name="nationalId" type="xs:string"/>
            <xs:element name="numberOfChildren" type="xs:nonNegativeInteger"/>
            <xs:element name="address" type="Address"/>
            <xs:element name="parents" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="parent" type="ParentType" minOccurs="0" maxOccurs="2"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="children" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="child" type="ChildType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ChildType">
        <xs:complexContent>
            <xs:extension base="PersonType">
                <xs:attribute name="gender" type="xs:string" use="required"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="ParentType">
        <xs:complexContent>
            <xs:extension base="PersonType">
                <xs:attribute name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:maxLength value="35"/>
                            <xs:minLength value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!-- Define root element -->
    <xs:element name="person" type="PersonType"/>

</xs:schema>

=== digilinq/trade-items/src/main/resources/xml/person.xml
<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="person.xsd">
    <firstName>string</firstName>
    <lastName>string</lastName>
    <birthday>2011-04-14</birthday>
    <nationalId>string</nationalId>
    <numberOfChildren>200</numberOfChildren>
    <address>
        <street>Boogschutter</street>
        <city>Amstelveen</city>
        <postalCode>1188 BS</postalCode>
    </address>
    <parents>
        <parent type="mother">
            <firstName>string</firstName>
            <lastName>string</lastName>
            <birthday>2011-04-14</birthday>
            <nationalId>string</nationalId>
            <numberOfChildren>200</numberOfChildren>
            <address>
                <street>string</street>
                <city>string</city>
                <postalCode>string</postalCode>
            </address>
        </parent>
        <parent type="father">
            <firstName>string</firstName>
            <lastName>string</lastName>
            <birthday>2011-04-14</birthday>
            <nationalId>string</nationalId>
            <numberOfChildren>200</numberOfChildren>
            <address>
                <street>string</street>
                <city>string</city>
                <postalCode>string</postalCode>
            </address>
        </parent>
    </parents>
    <children>
        <child gender="female">
            <firstName>Helma</firstName>
            <lastName>Mohammadi</lastName>
            <birthday>2017-03-27</birthday>
            <nationalId>1</nationalId>
            <numberOfChildren>0</numberOfChildren>
            <address>
                <street>Boogschutter</street>
                <city>Amstelveen</city>
                <postalCode>1188 BS</postalCode>
            </address>
        </child>
    </children>
</person>
